# python -m debugpy --listen 56766 --wait-for-client src/main.py -m \
python src/main.py \
    train.skip_train=True \
    model.use_pretrained_model=false \
    model.use_pretrained_embed=True \
    model.freeze_pretrained_embed=True \
    distilled_data.pretrained_data_path=./save/SASRec.music/clusters_20.spc_3.len_50.dim_32/2024-09-25.15-50-50/checkpoints/last-ckpt \
    base.gpu_id=1 \
    data.dataset_name=music \
    learner_train.train_step=200 \
    learner_train.batch_size_per_cluster=1 \
    train.epoch=50 \
    train.window=40 \
    train.batch_size_per_cluster=128 \
    train.lr_inputs_embeds=0.03 \
    train.inner_lr=0.005 \
    train.optimizer_type=adam \
    train.inner_optimizer_type=adam \
    train.scheduler_type=cosine \
    SASRec.n_heads=1 \
    SASRec.n_layers=1 \
    SASRec.hidden_size=32 \
    SASRec.inner_size=64 \
    SASRec.attn_dropout_prob=0.5 \
    SASRec.hidden_dropout_prob=0.2 \
    distilled_data.num_clusters=20 \
    distilled_data.seq_num_per_cluster=3 \
    distilled_data.seq_len=50 \
    distilled_data.seq_dim1=32 \
    distilled_data.seq_dim2=32
