SASRec:
  gpu_id: 1
  data_path: data/processed
  checkpoint_dir: checkpoint

  load_col:
    inter: [user_id, item_id, timestamp]
  MAX_ITEM_LIST_LENGTH: ${distilled_data.seq_len}
  train_neg_sample_args: ~

  eval_args:
    {
      "group_by": "user",
      "split": { "LS": "valid_and_test" },
      "order": "TO",
      "mode": { "valid": "uni100", "test": "uni100" },
    }

  topk: [5, 10, 20]
  metrics: ["Hit", "NDCG", "MRR", "Precision"]

  epochs: 500
  stopping_step: 20
  train_batch_size: ${data.train_batch_size}
  eval_batch_size: ${data.eval_batch_size}
  test_batch_size: ${data.test_batch_size}

  n_heads: 1
  n_layers: 1
  hidden_size: 32
  inner_size: 64
  hidden_dropout_prob: 0.2
  attn_dropout_prob: 0.5
  hidden_act: gelu
  layer_norm_eps: 1.0e-12
  initializer_range: 0.02
  loss_type: CE

  pretrain_epochs: 100
  pretrained_path: ${SASRec.checkpoint_dir}/SASRec-${data.dataset_name}.heads_${SASRec.n_heads}.layers_${SASRec.n_layers}.hiddens_${SASRec.hidden_size}.inners_${SASRec.inner_size}.maxlen_${SASRec.MAX_ITEM_LIST_LENGTH}.epochs_${SASRec.pretrain_epochs}.pth
