python src/main.py -m \
    base.gpu_id=1 \
    data.dataset_name=ml-1m \
    train.epochs=30 \
    train.window=40 \
    train.batch_size=32768 \
    train.seq_lr=0.03 \
    train.net_lr=0.01 \
    SASRec.n_heads=1 \
    SASRec.n_layers=1 \
    SASRec.hidden_size=32 \
    SASRec.inner_size=64 \
    SASRec.attn_dropout_prob=0.5 \
    SASRec.hidden_dropout_prob=0.2 \
    learner_train.train_step=200 \
    learner_train.batch_size=25 \
    distilled_data.seq_num=50 \
    distilled_data.seq_len=50 \
    distilled_data.seq_dim1=16 \
    distilled_data.seq_dim2=16
